name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - 4.11.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install XQuartz to macOS
        if: runner.os == 'macOS'
        run: brew install --cask xquartz

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Patch Graphics on Windows
        if: runner.os == 'Windows'
        run: opam pin add graphics git+https://github.com/ocaml/graphics

      - run: opam pin add bcotp.dev . --no-action

      - run: opam depext bcotp.dev --yes

      - run: opam install . --deps-only

      - run: opam exec -- dune build

      - name: Upload the build artifact
        uses: actions/upload-artifact@v2
        with:
          name: BCoTP-${{ matrix.os }}.exe
          path: _build/default/bin/main.exe
